;;; HTTP transport only. Segmentation, conjugation, lexical ranking, and glosses
;;; are Ichiran's own algorithms and dictionary, without application grammar rules.
(ql:quickload '(:ichiran :hunchentoot) :silent t)
(ichiran/mnt:add-errata)
(ichiran/conn:init-all-caches)
(ichiran/dict:init-suffixes t)
(defparameter *analysis-lock* (sb-thread:make-mutex :name "ichiran-analysis"))

(defun normalized-source (source)
  "Apply upstream normalization while carrying original code-point spans."
  (let* ((chars (map 'string (lambda (c) (or (ichiran/characters::to-normal-char c) c)) source))
         (rules (loop for (from to) on (append ichiran/characters::*punctuation-marks* ichiran/characters::*dakuten-join*) by #'cddr collect (cons from to)))
         (scanner (cl-ppcre:create-scanner (cons :alternation (mapcar #'car rules))))
         (cursor 0) (spans nil))
    (values
      (with-output-to-string (out)
        (cl-ppcre:do-matches (start end scanner chars)
          (loop for i from cursor below start do (write-char (char chars i) out) (push (list i (1+ i)) spans))
          (let ((replacement (cdr (assoc (subseq chars start end) rules :test #'equal))))
            (write-string replacement out)
            (loop repeat (length replacement) do (push (list start end) spans)))
          (setf cursor end))
        (loop for i from cursor below (length chars) do (write-char (char chars i) out) (push (list i (1+ i)) spans)))
      (coerce (nreverse spans) 'vector))))

(defun json-field (json key)
  (cdr (assoc key (cdr json) :test #'equal)))

(defparameter *sense-metadata* (make-hash-table))
(defun add-sense-identities (json seq)
  (when (and seq (integerp seq))
    (jsown:extend-js json ("seq" seq))
    (let ((raw (or (gethash seq *sense-metadata*)
                   (setf (gethash seq *sense-metadata*) (ichiran/dict::get-senses-raw seq)))))
      (loop for sense in (json-field json "gloss")
            for original = (find (json-field sense "gloss") raw :key (lambda (row) (getf row :gloss)) :test #'equal)
            when original do (jsown:extend-js sense ("ordinal" (getf original :ord))))))
  json)

(defun word-json (word)
  "Keep upstream head, dictionary sequence and sense-order metadata."
  (postmodern:with-connection ichiran/conn:*connection*
    (labels ((decorate-conjugation (json identities)
               (let ((identity (assoc (json-field json "reading") identities :test #'equal)))
                 (when identity (add-sense-identities json (cdr identity))))
               (loop for child in (json-field json "via") do (decorate-conjugation child identities)))
             (decorate (word json)
               (jsown:extend-js json ("primary" (ichiran/dict::word-info-primary word)))
               (let ((children (ichiran/dict:word-info-components word)))
                 (if children
                     (let ((key (if (ichiran/dict:word-info-alternative word) "alternative" "components")))
                       (loop for child in children for child-json in (jsown:val json key) do (decorate child child-json)))
                     (let* ((seq (ichiran/dict::word-info-seq word))
                            (text (ichiran/dict::word-info-true-text word))
                            (conjs (json-field json "conj")))
                       (add-sense-identities json seq)
                       (when (and seq text conjs)
                         (let* ((data (ichiran/dict::get-conj-data seq (ichiran/dict::word-info-conjugations word) text))
                                (identities (loop for (original source-seq) in (ichiran/dict::get-original-text* data text)
                                                  for reading = (car (ichiran/dict::find-words-seqs original source-seq))
                                                  when reading collect (cons (ichiran/dict::reading-str reading) source-seq))))
                           (loop for conj in conjs do (decorate-conjugation conj identities)))))))
               json))
      (decorate word (ichiran/dict:word-info-gloss-json word)))))

(defun analyze-source (source)
  (multiple-value-bind (text spans) (normalized-source source)
    (let ((offset 0) (tokens nil))
      (loop for (kind . chunk) in (ichiran/characters:basic-split text) do
        (when (eql kind :word)
          (loop for word in (ichiran/dict:simple-segment chunk :limit 1) do
            (let* ((start (+ offset (ichiran/dict:word-info-start word)))
                   (end (+ offset (ichiran/dict:word-info-end word))))
              (push (jsown:new-js
                      ("start" (first (aref spans start)))
                      ("end" (second (aref spans (1- end))))
                      ("word" (word-json word))) tokens))))
        (incf offset (length chunk)))
      (jsown:new-js ("tokens" (coerce (nreverse tokens) 'vector))))))

(defun json-response (fn)
  (setf (hunchentoot:content-type*) "application/json; charset=utf-8")
  (handler-case (sb-thread:with-mutex (*analysis-lock*) (jsown:to-json (funcall fn)))
    (error (condition)
      (format *error-output* "Ichiran request failed: ~a~%" condition)
      (setf (hunchentoot:return-code*) 500)
      (jsown:to-json (jsown:new-js ("error" "Ichiran analysis failed"))))))

(defun request-text (limit)
  (let* ((request (jsown:parse (hunchentoot:raw-post-data :force-text t))) (text (jsown:val request "text")))
    (unless (and (stringp text) (<= (length text) limit)) (error "Invalid text"))
    text))

(hunchentoot:define-easy-handler (health :uri "/health") ()
  (json-response (lambda ()
    (postmodern:with-connection ichiran/conn:*connection* (postmodern:query "SELECT 1"))
    (jsown:new-js ("status" "ready") ("engine" "ichiran") ("revision" "ea9583368e67cad22d94abae8dbcc8df96d99bcd") ("dictionary" "ichiran-260118")))))
(hunchentoot:define-easy-handler (analyze :uri "/analyze" :default-request-type :post) ()
  (json-response (lambda () (analyze-source (request-text 20000)))))
(hunchentoot:define-easy-handler (dictionary :uri "/dictionary" :default-request-type :post) ()
  (json-response (lambda ()
    (jsown:new-js ("entries" (coerce (mapcar #'word-json (ichiran/dict:find-word-info (request-text 512))) 'vector))))))
(hunchentoot:start (make-instance 'hunchentoot:easy-acceptor :port 8080 :address "0.0.0.0" :access-log-destination nil))
(format t "Ichiran HTTP service ready on port 8080~%")
(loop (sleep 60))
